### ISSUE TITLE
Update to cats-effect 3.0.0 milestones

### ISSUE THREAD

**Issue by kubukoz** [cb372/scalacache#450]
Just making an issue to track the progress for https://github.com/typelevel/cats-effect/issues/1330.

Current milestone is 3.0.0-M4.

This should be an easy one - if I remember correctly, we're only using Sync/Clock, possibly some Async in a couple places. The migration should be quite seamless with just some renames or updated imports, but I might be missing something.

If anyone wants to take a stab at this, it should be a good first issue :) I'm happy to help in case of any trouble.

**Comment by lewisjkl** [comment]
I will take a stab at this. I will update to the latest milestone and see how far I can get. Thanks for raising this!

**Comment by lewisjkl** [comment]
Turns out that the cats-effect milestones are not being cross built/published for ScalaJS yet (or at least I was having an issue figuring it out if it is). Since we are wanting to remove ScalaJS anyway (see #354), I went ahead and put together a PR (#452) to do so prior to upgrading to the latest 3.0.0 milestone.
