### ISSUE TITLE
Update to Caffeine v2.0.1

### ISSUE THREAD

**Issue by mdedetrich** [cb372/scalacache#74]
New version of Caffeine is out, which has substantial performance improvements (https://github.com/ben-manes/caffeine/tree/v2.0.1)

**Comment by cb372** [comment]
Do you have a link to any description of those performance improvements? In the Caffeine docs I can only find benchmarks against other libraries, nothing specific to v2 or v2.0.1

**Comment by mdedetrich** [comment]
Hmm, I think I may have misread the page (this was the performance improvement between Guava and Caffeine, not Caffeine and Caffeine 2).

The page is slightly confusing as it doesn't detail the difference between the major release, in which case, I don't think this is that high priority

**Comment by ben-manes** [comment]
The improvements are listed in the [Github release](https://github.com/ben-manes/caffeine/releases) section, which is supposedly the [idiomatic](https://github.com/blog/1547-release-your-software) way for maintaining release notes. Let me know if you think this should be linked on the main page, as I had thought that approach was well known.

The throughput performance in v2 is identical, as minor optimizations were offset by other changes. A planned optimization that I hoped would have a significant gain didn't pan out, but perhaps when I understand why it can be resurrected.

The major change in v2 is the adoption of a [near optimal](https://github.com/ben-manes/caffeine/wiki/Efficiency) eviction policy which outperforms ARC, LIRS, and (of course) LRU. It does so while being very memory efficient through the use of a frequency sketch instead of retaining evicted keys for history information. I'm collaborating with the original researchers on a paper that includes my contributions (windowing, optimizations, comparative analysis).

The API changes shouldn't affect `scalacache`. The primary difference was to make `RemovalListener` friendlier to Java's lambda expressions when constructing the builder.

**Comment by mdedetrich** [comment]
> The improvements are listed in the Github release section, which is supposedly the idiomatic way for maintaining release notes. Let me know if you think this should be linked on the main page, as I had thought that approach was well known.

Thanks, I swear I did see it somewhere however I was very tired at the time, so I probably didn't remember correctly

> The major change in v2 is the adoption of a near optimal eviction policy which outperforms ARC, LIRS, and (of course) LRU. It does so while being very memory efficient through the use of a frequency sketch instead of retaining evicted keys for history information. I'm collaborating with the original researchers on a paper that includes my contributions (windowing, optimizations, comparative analysis).

Yeah I think it should be fine, I don't think ScalaCache even uses `RemovalListener`

**Comment by cb372** [comment]
Sounds good to me! Thanks for the detailed info @ben-manes
